[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gotsol = "E6MRtJg483SVLY7EvryXJXPSLybRZyCCTsDY4BhNQYb"

[registry]
# url = "http://localhost:8899"
# url = "https://api.mainnet-beta.solana.com"
url = "https://api.devnet.solana.com" 

[provider]
# cluster = "mainnet"
cluster = "devnet"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/gotsol.ts"
init-global-devnet = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/init-global-devnet.ts"
init-global-mainnet = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/init-global-mainnet.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
